---
- name: assert | Test if drush_launcher_path is set correctly
  ansible.builtin.assert:
    quiet: true
    that:
      - drush_launcher_path is string
  when:
    - drush_launcher_path is defined
