---
- name: Import assert.yml
  ansible.builtin.import_tasks: assert.yml
  delegate_to: localhost
  run_once: true
- name: Update apt cache.
  ansible.builtin.apt:
    cache_valid_time: "600"
    update_cache: "true"
  when: ansible_os_family == 'Debian'
- name: Ensure unzip is installed.
  ansible.builtin.package:
    name: unzip
    state: present
- name: Install drush launcher.
  when: drush_launcher_install
  block:
    - name: Check current state.
      ansible.builtin.stat:
        path: "{{ drush_launcher_path }}"
      register: drush_path_state
    - name: Perform cleanup of old symlink.
      ansible.builtin.file:
        path: "{{ drush_launcher_path }}"
        state: absent
      when: drush_path_state.stat.islnk is defined and drush_path_state.stat.islnk
    - name: Ensure Drush path directory exists.
      ansible.builtin.file:
        mode: "0755"
        path: "{{ drush_launcher_path | dirname }}"
        state: directory
    - name: Install drush.
      ansible.builtin.get_url:
        dest: "{{ drush_launcher_path }}"
        mode: "0755"
        url: "{{ drush_launcher_phar_url }}"
    - name: Ensure drush is executable.
      ansible.builtin.file:
        mode: "0755"
        path: "{{ drush_launcher_path }}"
- name: Install drush composer.
  when: drush_composer_global_install
  block:
    - name: Ensure Drush is installed globally via Composer.
      community.general.composer:
        arguments: drush/drush:{{ drush_composer_version }}
        command: require
        global_command: true
      register: drush_composer_require
    - composer:
        arguments: drush/drush --with-dependencies
        command: update
        global_command: true
      name: update global Drush install if configured.
      tags:
        - skip_ansible_lint
      when:
        - drush_composer_update
        - not drush_composer_require.changed
    - name: Ensure globally-installed Drush is symlinked into bin dir.
      ansible.builtin.file:
        dest: "{{ drush_composer_path }}"
        src: "{{ drush_composer_global_bin_path }}/drush"
        state: link
- name: Install drush source.
  when: drush_install_from_source
  block:
    - name: Clone Drush from GitHub.
      ansible.builtin.git:
        depth: "{{ drush_clone_depth }}"
        dest: "{{ drush_source_install_path }}"
        force: "{{ drush_force_update }}"
        repo: https://github.com/drush-ops/drush.git
        update: "{{ drush_keep_updated }}"
        version: "{{ drush_source_install_version }}"
      register: drush_clone
    - name: Check for composer.json
      ansible.builtin.stat:
        cmd: drush_source_install_path }}/composer.json
        path: "{{"
      register: drush_composer
    - ansible.builtin.command: "{{ composer_path }} update {{ drush_composer_cli_options }} chdir={{ drush_source_install_path }}\n"
      name: ensure Drush can be installed on Debian Wheezy.
      tags:
        - skip_ansible_lint
      when:
        - drush_clone.changed and ansible_distribution == "Debian"
        - ansible_distribution_release == "wheezy"
        - drush_composer.stat.exists
    - ansible.builtin.command: "{{ composer_path }} install {{ drush_composer_cli_options }} chdir={{ drush_source_install_path }}\n"
      name: install Drush dependencies with Composer.
      tags:
        - skip_ansible_lint
      when: (drush_clone.changed and drush_composer.stat.exists) or drush_force_composer_install
    - name: Create drush symlink.
      ansible.builtin.file:
        dest: "{{ drush_source_install_bin_path }}"
        force: true
        src: "{{ drush_source_install_path }}/drush"
        state: link
    - name: Run drush to finish setting it up.
      ansible.builtin.command: "{{ drush_source_install_bin_path }}"
      become: false
      changed_when: "'Execute a drush command' not in drush_result.stdout"
      register: drush_result
